# Welcome to Jekyll!
#
# This config file affects your entire site. Once set up, you should rarely need to edit it.
# If you make changes, restart the server process.

# Basic Site Settings
locale: "en-US"
site_theme: "default"
title: "Nguyen Ngoc Yen Nhi - Portfolio"
title_separator: "-"
name: "Nguyen Ngoc Yen Nhi"
description: "Data Science Student & Researcher | Biostatistician Intern at OUCRU | Specializing in AI, Machine Learning, and Biostatistics"
url: "https://nhinguyen34.github.io"
baseurl: ""
repository: "NhiNguyen34/NhiNguyen34.github.io"

# Site Author Information
author:
  avatar: "profile.png"         # Ensure your profile image is placed in the appropriate folder
  name: "Nguyen Ngoc Yen Nhi"
  pronouns: "she/her"
  bio: "Bachelor of Science in Data Science at University of Information Technology (UIT), Vietnam. Dean’s List recipient and EVN Scholarship awardee. Experienced in biostatistics, AI, and machine learning, with active research and project work."
  location: "Ho Chi Minh City, Vietnam"
  employer: "Oxford University Clinical Research Unit (OUCRU)"
  email: "yennhi.nguyenngoc03@gmail.com"
  # Academic & Professional Profiles
  github: "NhiNguyen34"
  linkedin: "https://www.linkedin.com/in/yennhinguyenngoc03/"

# Social Sharing & Links
social:
  type: "Person"
  name: "Nguyen Ngoc Yen Nhi"
  links:
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/yennhinguyenngoc03/"
    - name: "GitHub"
      url: "https://github.com/NhiNguyen34"

# Publication Categories (if applicable)
publication_category:
  books:
    title: "Books"
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

# Site Settings
teaser: ""
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false
comments:
  provider: ""
staticman:
  allowedFields: ['name', 'email', 'url', 'message']
  branch: "gh-pages"
  commitMessage: "New comment."
  filename: comment-{@timestamp}
  format: "yml"
  moderation: true
  path: "_data/comments/{options.slug}"
  requiredFields: ['name', 'email', 'message']
  transforms:
    email: "md5"
  generatedFields:
    date:
      type: "date"
      options:
        format: "iso8601"
atom_feed:
  hide: false
  path: ""

# SEO & Analytics (update if you have verification codes)
google_site_verification: ""
bing_site_verification: ""
alexa_site_verification: ""
yandex_site_verification: ""
twitter:
  username: ""
facebook:
  username: ""
  app_id: ""
  publisher: ""
og_image: ""

analytics:
  provider: "false"
  google:
    tracking_id: ""

# File Inclusion & Exclusion
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Markdown & Conversion Settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections for Site Content
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Default Values for Pages & Posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS Settings
sass:
  sass_dir: _sass
  style: compressed

# Output Settings
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives Configuration
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression Settings
compress_html:
  clippings: all
  ignore:
    envs: development
